/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpempresas;

import java.awt.Color;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class EmpresasGestor extends javax.swing.JFrame {

    public EmpresasGestor() {
        initComponents();
        JTFRazon.requestFocus();
        mostrarEmpresas();
        mostrarEmpleados();
    }

    public void mostrarEmpresas() {
        Datos d = new Datos();

        String[] col = {"Razon social", "Cuit"};

        DefaultTableModel tm;
        tm = new DefaultTableModel(col, 0);

        for (Empresa e : d.allEmpresas()) {
            Object[] dato = {e.getRazonSocial(), e.getCuit()};
            tm.addRow(dato);
        }

        JTEmpresas.setModel(tm);

    }

    public void mostrarEmpleados() {
        Datos d = new Datos();

        String[] col = {"Documento", "Nombre y Apellido", "Sueldo", "Categoria", "Empresa"};

        DefaultTableModel tm;
        tm = new DefaultTableModel(col, 0);

        for (Empresa e : d.allEmpresas()) {
            for (Empleado em : e.getEmpleados()) {
                Object[] dato = {em.getDni(), em.getNombreApellido(), em.getSueldo(), em.getCategoria(), e.getRazonSocial()};
                tm.addRow(dato);
            }
        }

        JTEmpleados.setModel(tm);

    }

    public boolean isAllFill(String[] campos) {
        boolean flag = true;
        for (String s : campos) {
            if (s.isEmpty() || s.equals(" ")) {
                flag = false;
                break;
            }
        }
        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLRazonSocial = new javax.swing.JLabel();
        JLCuit = new javax.swing.JLabel();
        JTFRazon = new javax.swing.JTextField();
        JTFCuit = new javax.swing.JTextField();
        JBCrear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JLDocumento = new javax.swing.JLabel();
        JTFDocumento = new javax.swing.JTextField();
        JLNombre = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        JLApellido = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        JLSueldo = new javax.swing.JLabel();
        JTFSueldo = new javax.swing.JTextField();
        JCBCategoria = new javax.swing.JComboBox<>();
        JCBEmpresas = new javax.swing.JComboBox<>();
        JBAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTEmpleados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTEmpresas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(jPanel1.getBorder());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar Datos de la Empresa");

        JLRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLRazonSocial.setText("Razon Social :");

        JLCuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLCuit.setText("Cuit / Cuil : ");

        JTFCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFCuitKeyReleased(evt);
            }
        });

        JBCrear.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        JBCrear.setText("Crear Empresa");
        JBCrear.setEnabled(false);
        JBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JLCuit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addComponent(JTFRazon)
                        .addComponent(JLRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(JLRazonSocial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLCuit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(JBCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JLDocumento.setText("Documento : ");

        JLNombre.setText("Nombre : ");

        JLApellido.setText("Apellido : ");

        JLSueldo.setText("Sueldo :");

        JCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gerente", "Vendedor", "Contador", "Maquinista" }));

        JCBEmpresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        JBAgregar.setText("Agregar Empleado");
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresar Datos De Los Empleados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLDocumento)
                                    .addComponent(JLNombre)
                                    .addComponent(JLApellido)
                                    .addComponent(JLSueldo))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTFDocumento)
                                    .addComponent(JTFNombre)
                                    .addComponent(JTFApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(JTFSueldo)))
                            .addComponent(JBAgregar))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JCBEmpresas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCBCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDocumento)
                    .addComponent(JTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(JTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLApellido)
                    .addComponent(JTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSueldo)
                    .addComponent(JTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(JBAgregar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBorder(jPanel2.getBorder());

        JTEmpleados.setBackground(new java.awt.Color(153, 255, 255));
        JTEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTEmpleados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(jPanel2.getBorder());

        JTEmpresas.setBackground(new java.awt.Color(204, 0, 255));
        JTEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTEmpresas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCrearActionPerformed
        Datos d = new Datos();
        String rs = JTFRazon.getText();

        String cuit = JTFCuit.getText();
        if (!rs.isEmpty() && !cuit.isEmpty()) {
            try {
                Empresa e = new Empresa(rs, cuit);
                d.addEmpresa(e);
                JOptionPane.showMessageDialog(this, "Empresa creada con Exito");
                JCBEmpresas.addItem(rs);
                JTFRazon.setText("");
                JTFCuit.setText("");
                JTFRazon.requestFocus();
                mostrarEmpresas();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hubo un error al crear la empresa: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ambos campos deben estar llenos");
        }


    }//GEN-LAST:event_JBCrearActionPerformed

    private void JTFCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCuitKeyReleased
        // TODO add your handling code here:
        //CREAMOS EL PATRON PARA LA EXPRESION REGULAR
        String patron = "^[0-9]{2}[-][0-9]{8}[-][0-9]$";
        //CREAR EL OBJETO QUE COMPILARA EL PATRON DE LA EXPRESION REGULAR
        Pattern patt = Pattern.compile(patron);
        //CAPTURAR EL TEXTO QUE TIENE EL JTEXTFIELD
        String texto = JTFCuit.getText();

        //CREAR EL OBJETO MATCHER QUE COMPARARA EL TEXTO CON EL PATRON GENERADO
        Matcher match = patt.matcher(texto);

        //PREGUNTAR SI HA HECHO MATCH EL TEXTO CON EL PATRON Y HACER LAS ACCIONES CORRESPONDIENTES
        if (!match.matches()) {
            JTFCuit.setBackground(Color.red);
            JBCrear.setEnabled(false);

        } else {
            JTFCuit.setBackground(null);
            JBCrear.setEnabled(true);

        }


    }//GEN-LAST:event_JTFCuitKeyReleased

    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
        Datos d = new Datos();

        String dni = JTFDocumento.getText();
        String name = JTFNombre.getText();
        String surname = JTFApellido.getText();
        String sueldo = JTFSueldo.getText();
        String cat = JCBCategoria.getSelectedItem().toString();
        String emp = JCBEmpresas.getSelectedItem().toString();
        String[] campos = {dni, name, surname, sueldo, cat, emp};
        String sueldoPatt = "^[0-9]+([,][0-9]{2,})*$";
        Pattern patt = Pattern.compile(sueldoPatt);
        Matcher match = patt.matcher(sueldo);

        if (match.matches()) {
            if (isAllFill(campos)) {
                try {
                    Empleado trab = new Empleado(Integer.parseInt(dni), name + " " + surname, cat, Double.parseDouble(sueldo), d.buscarEmpresa(emp));
                    Empresa aux = d.buscarEmpresa(emp);
                    aux.agregarEmpleado(trab);
                    mostrarEmpleados();
                    JOptionPane.showMessageDialog(this, "Empleado Creado con exito!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Error en Formato de dato: " + e.getMessage());
                }

            } else {
                JOptionPane.showMessageDialog(this, "Hay campos que faltan datos, no te hagas el picaro!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El formato del sueldo esta mal ");
        }


    }//GEN-LAST:event_JBAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresasGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresasGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresasGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresasGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpresasGestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregar;
    private javax.swing.JButton JBCrear;
    private javax.swing.JComboBox<String> JCBCategoria;
    private javax.swing.JComboBox<String> JCBEmpresas;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLCuit;
    private javax.swing.JLabel JLDocumento;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLRazonSocial;
    private javax.swing.JLabel JLSueldo;
    private javax.swing.JTable JTEmpleados;
    private javax.swing.JTable JTEmpresas;
    private javax.swing.JTextField JTFApellido;
    private javax.swing.JTextField JTFCuit;
    private javax.swing.JTextField JTFDocumento;
    private javax.swing.JTextField JTFNombre;
    private javax.swing.JTextField JTFRazon;
    private javax.swing.JTextField JTFSueldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
